force-app/main/default/objects/Release__c/fields/PlannedDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedDate__c</fullName>
    <inlineHelpText>This field is mandatory if this is not a Release Backlog.</inlineHelpText>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/P_End_Date__c.field-meta.xml
<CustomField>
    <fullName>P_End_Date__c</fullName>
    <label>Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/P_Str_Date__c.field-meta.xml
<CustomField>
    <fullName>P_Str_Date__c</fullName>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/PlannedRelease__c.field-meta.xml
<CustomField>
    <fullName>PlannedRelease__c</fullName>
    <label>Planned Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Sprint_tst.cls
@isTest
private class Sprint_tst {
    @isTest static void test_method_one() {
        Project__c Projecto = new Project__c(name='Projecto uno');
        insert Projecto;
        Project__c Projecto2 = new Project__c(name='Projecto dos');
        insert Projecto2;
        
        Release__c rel = new Release__c(PlannedDate__c = Date.today());
        insert rel;
        Sprint__c SprintUno = new Sprint__c(Project__c = Projecto.id, PlannedRelease__c = rel.id, P_Str_Date__c  = date.today(), P_End_Date__c = date.today());
        insert SprintUno;
        Sprint__c SprintDos = new Sprint__c(Project__c = Projecto2.id, PlannedRelease__c = rel.id, P_Str_Date__c  = date.today(), P_End_Date__c = date.today(), status__c  = 'In Progress');
        insert SprintDos;
        SprintUno.status__c = 'In Progress';
        Update SprintUno;
        try{
        	SprintDos.status__c = 'In Progress';
        	Update SprintUno;
        }
        catch(exception e){
            system.assertEquals(true,e.getMessage().contains('Já existe um sprint em progresso nesse projeto'));
        }
        
        
        
    
    }

}