force-app/main/default/objects/ConfiguracoesSprint__c/fields/CriarBurndown__c.field-meta.xml
<CustomField>
    <fullName>CriarBurndown__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quando selecionado, criar SPrint Burndown automaticamente quando não encontrado pela história ao ser alterada para Accomplished</description>
    <label>Criar Burndown</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/PlannedDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedDate__c</fullName>
    <inlineHelpText>This field is mandatory if this is not a Release Backlog.</inlineHelpText>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/P_End_Date__c.field-meta.xml
<CustomField>
    <fullName>P_End_Date__c</fullName>
    <label>Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/P_Str_Date__c.field-meta.xml
<CustomField>
    <fullName>P_Str_Date__c</fullName>
    <label>Planned Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/PlannedRelease__c.field-meta.xml
<CustomField>
    <fullName>PlannedRelease__c</fullName>
    <label>Planned Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/ProductBacklog__c.field-meta.xml
<CustomField>
    <fullName>ProductBacklog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this sprint is a Product Backlog.</description>
    <inlineHelpText>Check this box if this Sprint is a Product Backlog.</inlineHelpText>
    <label>Product Backlog?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SprintBurndown__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Sprint Burndown</relationshipLabel>
    <relationshipName>Sprint_Burndown</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/ProductBacklog__c.field-meta.xml
<CustomField>
    <fullName>ProductBacklog__c</fullName>
    <description>Indicates if the History is in the Product Backlog.</description>
    <formula>Sprint__r.ProductBacklog__c</formula>
    <label>Product Backlog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Histórias</relationshipLabel>
    <relationshipName>Hist_rias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Sequence for stories construction.</description>
    <inlineHelpText>Define the sequence, in order of execution, for this story to be constructed.</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Histórias</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work__c/fields/Work_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Status__c</fullName>
    <label>Work Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Elaboration</fullName>
            </value>
            <value>
                <fullName>Functional Refinement</fullName>
            </value>
            <value>
                <fullName>Technical Refinement</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Unit Tests</fullName>
            </value>
            <value>
                <fullName>UAT Test</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Error Fixed</fullName>
            </value>
            <value>
                <fullName>Reay to Deploy</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Work_tst.cls
@isTest
public class Work_tst {
    @TestSetup static void CreateData(){
        Project__c Projecto = new Project__c(name='Projecto uno');
        insert Projecto;
        Release__c rel = new Release__c(PlannedDate__c = Date.today());
        insert rel;
        Project__c Projecto2 = new Project__c(name='Projecto dos');
        insert Projecto2;
        Sprint__c SprintUno = new Sprint__c(ProductBacklog__c = true, Project__c = Projecto.id, PlannedRelease__c = rel.id, P_Str_Date__c  = date.today(), P_End_Date__c = date.today());
        insert SprintUno;
        ConfiguracoesSprint__c param = new ConfiguracoesSprint__c(CriarBurndown__c = true);
        insert param;
        
        Sprint__c SprintDos = new Sprint__c(ProductBacklog__c = true, Project__c = Projecto2.id, PlannedRelease__c = rel.id, P_Str_Date__c  = date.today(), P_End_Date__c = date.today(), status__c ='In Progress');
        insert SprintDos;
    }
    @isTest static void Test_method_one(){
		Sprint__c Sprintuno = [select id from sprint__c limit 1];
        work__c FstW = new work__c(sprint__c = Sprintuno.id, sequence__c = 1);
        insert FstW;
        work__c SndW = new work__c(sprint__c = Sprintuno.id, sequence__c = 2);
        insert SndW;
        try{
            work__c ThrdW = new work__c(sprint__c = Sprintuno.id, sequence__c = 4);
        	insert ThrdW;
        }
        catch(exception e){
            system.assertEquals(true,e.getMessage().contains('Número de sequência fora do alcançe do sprint selecionado'));
            try{
                work__c FrthW = new work__c(sprint__c = Sprintuno.id, sequence__c = 0);
        		insert FrthW;
            }   
            catch(exception ex){
            	system.assertEquals(true,ex.getMessage().contains('Número de sequência fora do alcançe do sprint selecionado'));
            }
        }
        
        
    }
     @isTest static void Test_method_two(){
		list<Sprint__c> Sprints = [select id from sprint__c limit 2];
         
        work__c FstW = new work__c(sprint__c = Sprints[0].id, sequence__c = 1);
        insert FstW;
         
        work__c SndW = new work__c(sprint__c = Sprints[0].id, sequence__c = 2);
        insert SndW;
         
        work__c ThrdW = new work__c(sprint__c = Sprints[0].id, sequence__c = 3);
        insert ThrdW;
         
        Sndw.sequence__c =  1;
        update Sndw;
         
		system.assertEquals(2,[select sequence__c from work__c where id =: FstW.id].sequence__c);         
         
         try{
             Sndw.sequence__c =  2;
             ThrdW.sequence__c =  2;             
             Update new list<work__c>{Sndw,Thrdw};
             
         }
         catch(exception e){           
            
       		try{
                 ThrdW.sequence__c =  5;             
                 Update Thrdw;             
         	}
            catch(exception ex){
                //system.assertEquals(true,ex.getMessage().contains('Número de sequência fora do alcançe do sprint selecionado'));
            }
         }
         
     	
     }
      @isTest static void Test_method_three(){
		list<Sprint__c> Sprints = [select id from sprint__c];
        Sprints[0].Status__c ='In Progress';
        Update Sprints[0];
          
        work__c FstW = new work__c(sprint__c = Sprints[0].id, Points__c = 10);
        insert FstW;
        Fstw.Work_Status__c = 'Accomplished';
        Update Fstw;
          
        SprintBurndown__c burndown = new SprintBurndown__c(sprint__c = Sprints[0].id, date__c = Date.today());
        Insert burndown;
          
        Fstw.Work_Status__c = null;
        Update Fstw;
        
        delete burndown;
          
        Fstw.Work_Status__c = 'Accomplished';
        Update Fstw;
          
        Fstw.sprint__c = Sprints[1].id;
        Fstw.Work_Status__c = null;
        Update Fstw;
          
        system.assertequals(1,[select count() from SprintBurndown__c]);
         
      	
        
      }

}