force-app/main/default/objects/Defect__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
                <color>#FF0000</color>
                <label>Critical</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#FFFF66</color>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <color>#FFCC33</color>
                <label>Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <color>#66FF99</color>
                <label>Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#A845DC</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready to Test</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <color>#33CC00</color>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Melhoria</fullName>
            </value>
            <value>
                <fullName>Erro de procedimento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>SHORT description of defect.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Step__c.field-meta.xml
<CustomField>
    <fullName>Test_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Test Step</label>
    <referenceTo>Test_Steps__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Run</fullName>
                <color>#F3D904</color>
                <default>true</default>
                <label>No Run</label>
            </value>
            <value>
                <fullName>Pass</fullName>
                <color>#33CC00</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#CC0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DefectsController.cls
/**************************************************************************************************
 * Name: DefectsController
 * Object: Test_Steps__c, Defect__c
 * Purpose: This class is used to show all defects associated with the test steps
***************************************************************************************************/
public with sharing class DefectsController {
    public List<Defect__c> defectList {get; set;}

    private Id testStepId;

    /******************************************************************
    Purpose:  This method is the constructor
    *******************************************************************/
    public DefectsController() {
        testStepId = ApexPages.currentPage().getParameters().get('id');
        defectList = new List<Defect__c>();
        if(String.isNotBlank(testStepId)){
            queryDefects();
        }
    }

    /******************************************************************
    Purpose:  This method is used to query defects
    *******************************************************************/
    private void queryDefects(){
        defectList = [SELECT Name,
                             Severity__c,
                             Status__c,
                             Subject__c,
                             Assign_To__c
                      FROM Defect__c
                      WHERE Test_Step__c = :testStepId
                      ORDER BY Name DESC];
    }
}