force-app/main/default/objects/Defect__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <formula>Work__r.Sprint__r.Name</formula>
    <label>Sprint</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#A845DC</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready to Test</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <color>#33CC00</color>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Melhoria</fullName>
            </value>
            <value>
                <fullName>Erro de procedimento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>SHORT description of defect.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Step__c.field-meta.xml
<CustomField>
    <fullName>Test_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Test Step</label>
    <referenceTo>Test_Steps__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Test Cases</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Exec_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Exec_Date_time__c</fullName>
    <label>Exec Date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Run</fullName>
                <color>#F3D904</color>
                <default>true</default>
                <label>No Run</label>
            </value>
            <value>
                <fullName>Pass</fullName>
                <color>#33CC00</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#CC0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipName>Test_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewDefectController.cls
/**************************************************************************************************
 * Name: NewDefectController
 * Object: Defect__c
 * Purpose: This class is used to create defect for selected test step
***************************************************************************************************/
public with sharing class NewDefectController {
    public Defect__c defect {get; set;}
    public Boolean hasError {get; set;}

    private Id testStepId;
    private Test_Steps__c testStep;

    private static final String TEST_STEP_STATUS_FAILED = 'Failed';

    /******************************************************************
    Purpose:  This method is the constructor
    *******************************************************************/
    public NewDefectController() {
        testStepId = ApexPages.currentPage().getParameters().get('id');
        getTestStep();
        initialDefect();

        // set hasError as true to validate the mandatory field
        hasError = true;
    }

    /******************************************************************
    Purpose:  This method is used to initial defect
    *******************************************************************/
    public void initialDefect(){
        defect = new Defect__c();
        defect.Test_Step__c = testStepId;
        defect.Test_Case__c = testStep.Test_Case__c;
        defect.Subject__c = testStep.Test_Case__r.Subject__c;
        defect.Project__c = testStep.Test_Case__r.Sprint__r.Project__c;
    }

    /******************************************************************
    Purpose:  This method is used to save defect
    ******************************************************************/
    public void saveDefect(){
        hasError = false;
        try{
            System.debug(LoggingLevel.INFO, '*** defect: ' + defect);
            insert defect;

            testStep.Status__c = TEST_STEP_STATUS_FAILED;
            testStep.Exec_Date_time__c = Datetime.now();
            update testStep;
        }catch (DMLException ex){
            hasError = true;
            for(Integer i = 0; i < ex.getNumDml(); i++){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getDmlMessage(i)));
            }
            return;
        }
    }

    /******************************************************************
    Purpose:  This method is used to get test step by test step id
    ******************************************************************/
    private void getTestStep(){
        testStep = [SELECT  Id, 
                            Status__c,
                            Exec_Date_time__c,
                            Test_Case__c,
                            Test_Case__r.Subject__c,
                            Test_Case__r.Sprint__r.Project__c
                    FROM Test_Steps__c
                    WHERE Id = :testStepId ];
    }
}