force-app/main/default/objects/Defect__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <formula>Work__r.Sprint__r.Name</formula>
    <label>Sprint</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <formula>if( ISBLANK( Test_Case__c ), Test_Step__r.Test_Case__r.Test_Scenario__r.Name  ,   Test_Case__r.Test_Scenario__r.Name )</formula>
    <label>Test Scenario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Release__c/fields/PlannedDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedDate__c</fullName>
    <inlineHelpText>This field is mandatory if this is not a Release Backlog.</inlineHelpText>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/PlannedRelease__c.field-meta.xml
<CustomField>
    <fullName>PlannedRelease__c</fullName>
    <label>Planned Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Show_In_Test_Console__c.field-meta.xml
<CustomField>
    <fullName>Show_In_Test_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show In Test Console</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Test Cases</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Scenario</label>
    <referenceTo>Test_Scenario__c</referenceTo>
    <relationshipLabel>Test Cases</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipName>Test_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassUpdateTestStepsExtTest.cls
/**************************************************************************************************
 * Name: TestCaseConsoleControllerTest
 * Object: Test_Case__c, Test_Steps__c, Defect__c
 * Purpose: A test class for MassUpdateTestStepsExt
 **************************************************************************************************/
@isTest
private class MassUpdateTestStepsExtTest {
    static testMethod void testMassUpdateTestStepsExt() {

        Project__c project = new Project__c(
            Name = 'Project Test');

        insert project;
        
        Release__c release = new Release__c(
            Name = 'Release Test',
            PlannedDate__c = Date.newInstance(1960, 2, 17));
        
        insert release;

        Sprint__c sprint = new Sprint__c(
            Project__c = project.Id,
            PlannedRelease__c = release.Id,
            Show_In_Test_Console__c = TRUE);

        insert sprint;

        Test_Scenario__c scenario = new Test_Scenario__c(
            Name = 'Scenario A');

        insert scenario;

        Test_Case__c testCase = new Test_Case__c(
            Test_Scenario__c = scenario.Id,
            Sprint__c = sprint.Id);

        insert testCase;

        Test_Steps__c testStep = new Test_Steps__c(
            Test_Case__c = testCase.Id);

        insert testStep;

        PageReference testPage = Page.MassUpdateTestSteps;
        Test.setCurrentPage(testPage);

        ApexPages.StandardController testCaseController = new ApexPages.StandardController(testCase);
        MassUpdateTestStepsExt testStepExt = new MassUpdateTestStepsExt(testCaseController);
        
        String nextPage = testStepExt.saveTestSteps().getUrl();

        System.assertEquals(TRUE, nextPage.contains(testCase.Id));

        String cancelPage = testStepExt.cancelTestSteps().getUrl();

        System.assertEquals(TRUE, cancelPage.contains(testCase.Id));
    }
}