force-app/main/default/objects/Defect__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <formula>Work__r.Sprint__r.Name</formula>
    <label>Sprint</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <formula>if( ISBLANK( Test_Case__c ), Test_Step__r.Test_Case__r.Test_Scenario__r.Name  ,   Test_Case__r.Test_Scenario__r.Name )</formula>
    <label>Test Scenario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Test Cases</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Scenario</label>
    <referenceTo>Test_Scenario__c</referenceTo>
    <relationshipLabel>Test Cases</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipName>Test_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TestCaseConsoleTreeView__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScrumTrackerTest.cls
@isTest
private class ScrumTrackerTest {
    @isTest
    private static void TestMassUpdateTestSteps_saveTestSteps(){
        Project__c p = ScrumTrackerTestData.createProject();
        Release__c r = ScrumTrackerTestData.createRelease();
        Sprint__c sp = ScrumTrackerTestData.createSprint(p, r);
        Test_Scenario__c tsc = ScrumTrackerTestData.createTestScenario();
        Test_Case__c tc = ScrumTrackerTestData.createTestCase(tsc, sp);
        Test_Steps__c ts01 = ScrumTrackerTestData.createTestStep(tc);
        Test_Steps__c ts02 = ScrumTrackerTestData.createTestStep(tc);

        Test.startTest();

        MassUpdateTestStepsExt massUpdateTestSteps = new MassUpdateTestStepsExt(new ApexPages.StandardController(tc));
        massUpdateTestSteps.saveTestSteps();

        Test.stopTest();
    }

    @isTest
    private static void TestMassUpdateTestSteps_cancelTestSteps(){
        Project__c p = ScrumTrackerTestData.createProject();
        Release__c r = ScrumTrackerTestData.createRelease();
        Sprint__c sp = ScrumTrackerTestData.createSprint(p,r);
        Test_Scenario__c tsc = ScrumTrackerTestData.createTestScenario();
        Test_Case__c tc = ScrumTrackerTestData.createTestCase(tsc, sp);
        Test_Steps__c ts01 = ScrumTrackerTestData.createTestStep(tc);
        Test_Steps__c ts02 = ScrumTrackerTestData.createTestStep(tc);

        Test.startTest();

        MassUpdateTestStepsExt massUpdateTestSteps = new MassUpdateTestStepsExt(new ApexPages.StandardController(tc));
        massUpdateTestSteps.cancelTestSteps();

        Test.stopTest();
    }

    @isTest
    private static void TestNewDefect(){
        Project__c p = ScrumTrackerTestData.createProject();
        Release__c r = ScrumTrackerTestData.createRelease();
        Sprint__c sp = ScrumTrackerTestData.createSprint(p,r);
        Test_Scenario__c tsc = ScrumTrackerTestData.createTestScenario();
        Test_Case__c tc = ScrumTrackerTestData.createTestCase(tsc, sp);
        Test_Steps__c ts01 = ScrumTrackerTestData.createTestStep(tc);
        Test_Steps__c ts02 = ScrumTrackerTestData.createTestStep(tc);

        Test.startTest();

        ApexPages.currentPage().getParameters().put('id', ts01.Id);
        NewDefectController newDef = new NewDefectController();
        newDef.saveDefect();

        Test.stopTest();
    }

    @isTest
    private static void TestTestCaseConsole(){
        Project__c p = ScrumTrackerTestData.createProject();
        Release__c r = ScrumTrackerTestData.createRelease();
        Sprint__c sp = ScrumTrackerTestData.createSprint(p,r);
        Test_Scenario__c tsc = ScrumTrackerTestData.createTestScenario();
        Test_Case__c tc = ScrumTrackerTestData.createTestCase(tsc, sp);
        Test_Steps__c ts01 = ScrumTrackerTestData.createTestStep(tc);
        Test_Steps__c ts02 = ScrumTrackerTestData.createTestStep(tc);

        TestCaseConsoleTreeView__c node = new TestCaseConsoleTreeView__c();
        node.Name = 'OpenNode1';
        node.Project__c = 'Mid-market call center bid';
        node.Active__c = true;
        insert node;

        Test.startTest();

        TestCaseConsoleController testCaseConsole = new TestCaseConsoleController();

        testCaseConsole.selectedScenarioId = tsc.Id;
        testCaseConsole.selectedSprintId = sp.Id;
        testCaseConsole.queryTestCasesBySprintIdAndScenarioId();

        testCaseConsole.selectedTestCaseId = tc.Id;
        testCaseConsole.queryTestStepsByTestCaseId();

        testCaseConsole.getTestScenarioPrefix();

        testCaseConsole.saveTestSteps();

        Test.stopTest();
    }

    @isTest
    private static void TestDefectsController(){
        Project__c p = ScrumTrackerTestData.createProject();
        Release__c r = ScrumTrackerTestData.createRelease();
        Sprint__c sp = ScrumTrackerTestData.createSprint(p,r);
        Test_Scenario__c tsc = ScrumTrackerTestData.createTestScenario();
        Test_Case__c tc = ScrumTrackerTestData.createTestCase(tsc, sp);
        Test_Steps__c ts = ScrumTrackerTestData.createTestStep(tc);
        Defect__c def01 = ScrumTrackerTestData.createDefect(ts);
        Defect__c def02 = ScrumTrackerTestData.createDefect(ts);

        Test.startTest();

        DefectsController defectsController = new DefectsController();

        Test.stopTest();
    }    
}