force-app/main/default/objects/Defect__c/fields/Related_Defect__c.field-meta.xml
<CustomField>
    <fullName>Related_Defect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Defect</label>
    <referenceTo>Defect__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#A845DC</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Ready to Test</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <color>#33CC00</color>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Melhoria</fullName>
            </value>
            <value>
                <fullName>Erro de procedimento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>SHORT description of defect.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Test_Step__c.field-meta.xml
<CustomField>
    <fullName>Test_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Test Step</label>
    <referenceTo>Test_Steps__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEV</fullName>
                <default>true</default>
                <label>DEV</label>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Expected_Results__c.field-meta.xml
<CustomField>
    <fullName>Expected_Results__c</fullName>
    <label>Expected Results</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <label>Plan Start Date</label>
    <summarizedField>Test_Steps__c.Plan_Start_Date__c</summarizedField>
    <summaryForeignKey>Test_Steps__c.Test_Case__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEV</fullName>
                <default>true</default>
                <label>DEV</label>
            </value>
            <value>
                <fullName>HMG</fullName>
            </value>
            <value>
                <fullName>PROD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Actual_Results__c.field-meta.xml
<CustomField>
    <fullName>Actual_Results__c</fullName>
    <label>Actual Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Exec_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Exec_Date_time__c</fullName>
    <label>Exec Date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Expected_Results__c.field-meta.xml
<CustomField>
    <fullName>Expected_Results__c</fullName>
    <label>Expected Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Run</fullName>
                <color>#F3D904</color>
                <default>true</default>
                <label>No Run</label>
            </value>
            <value>
                <fullName>Pass</fullName>
                <color>#33CC00</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#CC0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Step_Details__c.field-meta.xml
<CustomField>
    <fullName>Step_Details__c</fullName>
    <label>Step Details</label>
    <length>13100</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipName>Test_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Test_Steps__c/fields/Tester__c.field-meta.xml
<CustomField>
    <fullName>Tester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Script</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MassUpdateTestStepsExt.cls
/**************************************************************************************************
 * Name: MassUpdateTestStepsExt
 * Object: Test_Case__c, Test_Steps__c, Defect__c
 * Purpose: This class is used to run test steps in one page and create defects for the failed steps
***************************************************************************************************/
public with sharing class MassUpdateTestStepsExt {
    public Test_Case__c testCase {get; set;}
    public Map<Id, List<Defect__c>> testStepIdDefectsMap {get; set;}
    public Map<Id, Integer> testStepIdDefectNumberMap {get; set;}
    public List<Test_Steps__c> testStepList {get; set;}
    public Boolean hasError {get; set;}

    private Map<Id, Test_Steps__c> testStepMap;

    /******************************************************************
    Purpose:  This method is the constructor
    *******************************************************************/
    public MassUpdateTestStepsExt(ApexPages.StandardController con) {
        testCase = (Test_Case__c)con.getRecord();
        hasError = false;
        testStepIdDefectsMap = new Map<Id, List<Defect__c>>();
        testStepIdDefectNumberMap = new Map<Id, Integer>();
        getTestCaseAndTestSteps();
    }

    /******************************************************************
    Purpose:  This method is return test case page
    ******************************************************************/
    public PageReference cancelTestSteps(){
        PageReference pr = new PageReference('/' + testCase.Id);
        pr.setRedirect(true);
        return pr;
    }

    /******************************************************************
    Purpose:  This method is used to save test steps
    ******************************************************************/
    public PageReference saveTestSteps(){
        List<Test_Steps__c> tsList = new List<Test_Steps__c>();
        for(Test_Steps__c ts : testStepList){
            Test_Steps__c ots = testStepMap.get(ts.Id);
            //set executed date time if status changed
            if(ots.Status__c != ts.Status__c 
                || ots.Actual_Results__c != ts.Actual_Results__c){
                ts.Exec_Date_time__c = Datetime.now();
            }
            tsList.add(ts);
        }
        try{
            update tsList;
        }catch (DMLException ex){
            for(Integer i = 0; i < ex.getNumDml(); i++){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getDmlMessage(i)));
            }
        }

        PageReference pr = new PageReference('/' + testCase.Id);
        pr.setRedirect(true);
        return pr;
    }

    /******************************************************************
    Purpose:  This method is used to get test case and its test steps by test case id
    ******************************************************************/
    public void getTestCaseAndTestSteps(){
        testCase = [SELECT  Id,
                            Subject__c,
                            Type__c
                    FROM Test_Case__c 
                    WHERE Id = :testCase.Id];
            
        testStepIdDefectsMap = new Map<Id, List<Defect__c>>();
        testStepIdDefectNumberMap = new Map<Id, Integer>();
        testStepList = [SELECT  Id, 
                                Name,
                                Sequence__c,
                                Status__c,
                                Step_Details__c,
                                Expected_Results__c,
                                Actual_Results__c,
                                Plan_Start_Date__c,
                                Exec_Date_time__c,
                                Tester__r.Name,
                                (SELECT Name 
                                FROM Defects__r
                                ORDER BY Name DESC)
                       FROM Test_Steps__c
                       WHERE Test_Case__c = :testCase.Id];
        
        testStepMap = new Map<Id, Test_Steps__c>();
        for(Test_Steps__c ts : testStepList){
            testStepMap.put(ts.Id, ts);
            if(!testStepIdDefectsMap.containsKey(ts.Id)){
                testStepIdDefectsMap.put(ts.Id, new List<Defect__c>());
            }
            for(Defect__c def : ts.Defects__r){
                testStepIdDefectsMap.get(ts.Id).add(def);
            }
            if(!testStepIdDefectNumberMap.containsKey(ts.Id)){
                testStepIdDefectNumberMap.put(ts.Id, ts.Defects__r.size());
            }
        }
    }

}